### ISSUE TITLE
How to understand the DOOM code

### ISSUE THREAD

**Issue by KiranKanchi** [Yuanzjls/Doom_STM32F769-DISCO#2]
Hi Yuan,

Thank you so much for sharing the full project on DOOM, really appreciate your help.
Do you by any chance know what resource to follow in order to understand how Doom works on STM32 ?

Kind regards,
Kiran Kanchi

**Comment by Yuanzjls** [comment]
I don't know honestly. I did not dig into the source code very deeply. I port the code from [here](https://github.com/floppes/stm32doom)
